with source as (
        select * from {{ source('src_spend', 'feb_spend_2024') }}
  ),
  renamed as (
      select
          {{ adapter.quote("_dbt_source_relation") }},
        {{ adapter.quote("invoiceSectionName") }},
        {{ adapter.quote("accountName") }},
        {{ adapter.quote("accountOwnerId") }},
        {{ adapter.quote("subscriptionId") }},
        {{ adapter.quote("subscriptionName") }},
        {{ adapter.quote("resourceGroup") }},
        {{ adapter.quote("resourceLocation") }},
        {{ adapter.quote("date") }},
        {{ adapter.quote("productName") }},
        {{ adapter.quote("meterCategory") }},
        {{ adapter.quote("meterSubCategory") }},
        {{ adapter.quote("meterId") }},
        {{ adapter.quote("meterName") }},
        {{ adapter.quote("meterRegion") }},
        {{ adapter.quote("unitOfMeasure") }},
        {{ adapter.quote("quantity") }},
        {{ adapter.quote("effectivePrice") }},
        {{ adapter.quote("costInBillingCurrency") }},
        {{ adapter.quote("costCenter") }},
        {{ adapter.quote("consumedService") }},
        {{ adapter.quote("resourceId") }},
        {{ adapter.quote("tags") }},
        {{ adapter.quote("offerId") }},
        {{ adapter.quote("additionalInfo") }},
        {{ adapter.quote("serviceInfo1") }},
        {{ adapter.quote("serviceInfo2") }},
        {{ adapter.quote("resourceName") }},
        {{ adapter.quote("reservationId") }},
        {{ adapter.quote("reservationName") }},
        {{ adapter.quote("unitPrice") }},
        {{ adapter.quote("productOrderId") }},
        {{ adapter.quote("productOrderName") }},
        {{ adapter.quote("term") }},
        {{ adapter.quote("publisherType") }},
        {{ adapter.quote("publisherName") }},
        {{ adapter.quote("chargeType") }},
        {{ adapter.quote("frequency") }},
        {{ adapter.quote("pricingModel") }},
        {{ adapter.quote("availabilityZone") }},
        {{ adapter.quote("billingAccountId") }},
        {{ adapter.quote("billingAccountName") }},
        {{ adapter.quote("billingCurrencyCode") }},
        {{ adapter.quote("billingPeriodStartDate") }},
        {{ adapter.quote("billingPeriodEndDate") }},
        {{ adapter.quote("billingProfileId") }},
        {{ adapter.quote("billingProfileName") }},
        {{ adapter.quote("invoiceSectionId") }},
        {{ adapter.quote("isAzureCreditEligible") }},
        {{ adapter.quote("partNumber") }},
        {{ adapter.quote("payGPrice") }},
        {{ adapter.quote("planName") }},
        {{ adapter.quote("serviceFamily") }},
        {{ adapter.quote("costAllocationRuleName") }},
        {{ adapter.quote("invoiceId") }},
        {{ adapter.quote("previousInvoiceId") }},
        {{ adapter.quote("resellerName") }},
        {{ adapter.quote("resellerMpnId") }},
        {{ adapter.quote("servicePeriodEndDate") }},
        {{ adapter.quote("servicePeriodStartDate") }},
        {{ adapter.quote("productId") }},
        {{ adapter.quote("publisherId") }},
        {{ adapter.quote("resourceGroupName") }},
        {{ adapter.quote("location") }},
        {{ adapter.quote("billingCurrency") }},
        {{ adapter.quote("pricingCurrency") }},
        {{ adapter.quote("costInPricingCurrency") }},
        {{ adapter.quote("costInUsd") }},
        {{ adapter.quote("paygCostInBillingCurrency") }},
        {{ adapter.quote("paygCostInUsd") }},
        {{ adapter.quote("exchangeRatePricingToBilling") }},
        {{ adapter.quote("exchangeRateDate") }},
        {{ adapter.quote("benefitId") }},
        {{ adapter.quote("benefitName") }},
        {{ adapter.quote("provider") }}

      from source
  )
  select * from renamed
    